### PR TITLE
Further overmap updates

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This updates the fields to current C: DDA standard. Considering the number of people still playing old experimentals due to recent mechanics, it might be a good idea to create another legacy branch before merging these changes.

### CODE REVIEW

**Comment by DangerNoodle** [comment]
Closed? I suppose a legacy build would be good then.

**Comment by DangerNoodle** [comment]
Legacy branch added here: https://github.com/DangerNoodle/mining-mod/tree/legacy-2-predates-no_rotate

It includes your last pull request, however. Should it be reverted for that branch?

**Comment by BorkBorkGoesTheCode** [comment]
I closed because the PR isn't sufficient to replicate the old behavior in the new format. Will reopen in future

**Comment by DangerNoodle** [comment]
Understood.

**Pull request closed without merging**
